### ISSUE TITLE
github Action 스크립트 수정

### ISSUE THREAD

**Issue by ShinSeongCheol** [TKBus/client#3]
### 📄 설명

- 특정 소스 파일만 트리거 작동하도록 경로 지정
- 빌드 완료 시 디스코드로 알림 발송

### ✅ 작업할 내용

- [x] 트리거 작동 기준 소스 코드에 대한 **IF문** 추가
- [x] 디스코드 연동 및 알림 발생 **Hook** 추가

**Comment by kimhaechang1** [comment]
develop 브랜치 기준으로 아래의 파일 및 경로 수정시 CI/CD 작동
- src/**
- public/**
- Dockerfile
- package.json
- package-lock.json
- vite.config.js

디스코드 연동해놨고, CI/CD 성공/실패 여부 알림봇 생성완료
